apiVersion : apps/v1
kind: Deployment
metadata:
  name: frontendmodel 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendmodel
  template:
    metadata:
      labels:
        app: frontendmodel 
    spec:
      containers:
        - name: frontendmodel 
          image: acrcaserestmarcio.azurecr.io/frontendmodel
          ports:
          - containerPort: 5000